In [1]:
#importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

In [2]:
#reading the dataset
df=pd.read_csv("C:\\Users\\Sanjeet Dhume\\Downloads\\project.csv" , sep=';')

In [3]:
#Viewwing head of data set
df.head()

ID        age  systolic_bp  diastolic_bp  cholesterol    prognosis
0   0  77.196340    85.288742     80.021878    79.957109  retinopathy
1   1  63.529850    99.379736     84.852361   110.382411  retinopathy
2   2  69.003986   111.349455    109.850616   100.828246  retinopathy
3   3  82.638210    95.056128     79.666851    87.066303  retinopathy
4   4  78.346286   109.154591     90.713220    92.511770  retinopathy

In [4]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [5]:
ls

 Volume in drive C is Windows
 Volume Serial Number is D453-627B

 Directory of C:\Users\Sanjeet Dhume\Documents\ExcelR

21-09-2022  21:34    <DIR>          .
15-06-2022  13:04    <DIR>          ..
21-09-2022  21:34    <DIR>          .ipynb_checkpoints
16-03-2022  21:07            30,582 Afinn.csv
19-03-2022  23:59           120,309 AI [Regression ].ipynb
21-06-2022  03:25             1,705 amazon-search
16-03-2022  21:07            23,666 apple.txt
04-06-2022  20:52           184,255 association  rules assignment 2.ipynb
14-04-2022  16:33            88,268 association rules assignment 1.ipynb
01-03-2022  22:01            59,350 Association Rules.ipynb
24-07-2022  01:48            44,167 Bagging_Random Forest_Boosting_Stacking.ipynb
24-02-2022  20:44             3,527 Cars.csv
15-02-2022  20:45         1,794,881 Chapter 2_ Sampling Distributions and Confidence Intervals - Natural Resources Biometrics.pdf
15-02-2022  20:46         3,432,196 Chapter 3_ Hypothesis Testing - Natural Resour

In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [13]:
from sklearn import preprocessing

In [14]:
label=preprocessing.LabelEncoder()
df['age']=label.fit_transform(df.age)
df['systolic_bp']=label.fit_transform(df.systolic_bp)
df['diastolic_bp']=label.fit_transform(df.diastolic_bp)
df['cholesterol']=label.fit_transform(df.cholesterol)
df['prognosis']=label.fit_transform(df.prognosis)

In [15]:
df

ID   age  systolic_bp  diastolic_bp  cholesterol  prognosis
0        0  5784          369           802           76          1
1        1  3977         2821          1763         4991          1
2        2  5059         5066          5801         3158          1
3        3  5932         1900           738          526          1
4        4  5831         4739          3170         1363          1
...    ...   ...          ...           ...          ...        ...
5995  5995   562         1847          2181         4572          0
5996  5996  3887         2981          3847         4055          1
5997  5997  1792         2614          5343         5793          1
5998  5998  3962         4373          2531         4264          1
5999  5999  3752         2323          2238         4749          0

[6000 rows x 6 columns]

In [16]:
# Dividing our data into input and output variables 
X = df.iloc[:,1:]
Y = df.iloc[:,0]

In [17]:
X

age  systolic_bp  diastolic_bp  cholesterol  prognosis
0     5784          369           802           76          1
1     3977         2821          1763         4991          1
2     5059         5066          5801         3158          1
3     5932         1900           738          526          1
4     5831         4739          3170         1363          1
...    ...          ...           ...          ...        ...
5995   562         1847          2181         4572          0
5996  3887         2981          3847         4055          1
5997  1792         2614          5343         5793          1
5998  3962         4373          2531         4264          1
5999  3752         2323          2238         4749          0

[6000 rows x 5 columns]

In [18]:
Y

0          0
1          1
2          2
3          3
4          4
        ... 
5995    5995
5996    5996
5997    5997
5998    5998
5999    5999
Name: ID, Length: 6000, dtype: int64

In [19]:
#Logistic regression and fit the model
classifier = LogisticRegression()
classifier.fit(X,Y)

LogisticRegression()

In [20]:
classifier.intercept_

array([-1.66922983e-06, -4.11930532e-06, -1.42122417e-05, ...,
       -9.53442148e-06, -3.04155954e-06, -1.61857385e-06])

In [21]:
classifier.coef_

array([[ 5.21279706e-02, -3.59558401e-02, -2.54465940e-02,
        -4.40726361e-02,  1.71502383e-05],
       [ 9.89423542e-03, -7.01988366e-03, -2.54850545e-02,
         3.15913582e-02,  1.42044161e-05],
       [ 6.99614448e-03,  8.00481712e-03,  2.11410661e-02,
        -2.05496050e-02,  7.16036752e-06],
       ...,
       [-2.90874623e-02, -2.15488328e-02,  2.18151989e-02,
         2.97767695e-02,  1.52371718e-05],
       [ 6.34661014e-03,  1.53460065e-02, -1.88028832e-02,
         1.36730729e-02,  1.17862365e-05],
       [ 9.68211451e-03, -1.44976010e-02, -1.58669517e-02,
         3.17364392e-02, -1.90231456e-05]])

In [22]:
#Predict for X dataset
y_pred = classifier.predict(X)

In [23]:
y_pred_df= pd.DataFrame({'actual': Y,
                         'predicted_values': classifier.predict(X)})

In [24]:
y_pred_df

actual  predicted_values
0          0                 0
1          1                 1
2          2                 2
3          3              5738
4          4                 4
...      ...               ...
5995    5995              5995
5996    5996              5996
5997    5997              5997
5998    5998              5998
5999    5999              1693

[6000 rows x 2 columns]

In [25]:
# Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix = confusion_matrix(Y,y_pred)
print (confusion_matrix)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [26]:
ac(Y,y_pred)

0.5951666666666666

In [27]:
#Classification report
from sklearn.metrics import classification_report
print(classification_report(Y,y_pred))

              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           1       1.00      1.00      1.00         1
           2       0.50      1.00      0.67         1
           3       0.00      0.00      0.00         1
           4       0.50      1.00      0.67         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.33      1.00      0.50         1
          10       0.25      1.00      0.40         1
          11       1.00      1.00      1.00         1
          12       0.50      1.00      0.67         1
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       0.00      0.00      0.00         1
          16       1.00      1.00      1.00         1
          17       0.00    